version: 2

defaults: &defaults
  docker:
    - image: circleci/node:11.10.0

  working_directory: ~/repo

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: .
          paths:
            - packages/**/types
            - packages/**/dist
            - node_modules

  unit-test:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: Unit Tests
          command: npm run test:unit

  integration-test:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: Integration Tests
          command: npm run test:integration

workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      - unit-test:
          requires:
            - build
      - integration-test:
          requires:
            - build
